#! /bin/sh
set -e
trap "rm -f $$" EXIT INT HUP TERM
../src/ssh-adverb --version > $$
read v < $$
case $v in
"ssh-adverb "* )
  ;;
* )
  echo "ERROR: unexpected --version output: $v" >&2
  exit 1
  ;;
esac
