#! /bin/sh
set -e
trap "rm -f $$" EXIT
SSH_ADVERB_CMD=${top_srcdir:-..}/test/ssh-report \
SSH_REPORT_OUTPUT=$$ \
    ../src/ssh-adverb host echo '>spong'
diff -u ${top_srcdir:-..}/test/test-redirect-expect $$

SSH_ADVERB_CMD=${top_srcdir:-..}/test/ssh-do \
SSH_DO_OUTPUT=$$ \
    ../src/ssh-adverb host echo '>spong'
diff -u ${top_srcdir:-..}/test/test-redirect-do-expect $$
